# Site settings
url: "https://opendevelopmentmethod.org"
domain: opendevelopmentmethod.org

title: Open Development Methodology
description: >
  As the world continues to evolve around us, it makes sense that our software development methods should evolve, too. Join the discussion to shape a new generation of Software Development Methodology.

author:
  name: Ahmad Nassri
  link: https://www.ahmadnassri.com/about
  facebook_id: 227304446

links:
  email: info@opendevelopmentmethod.org
  github: https://github.com/OpenDevelopmentMethod/discussion

# Build settings
markdown: kramdown
timezone: America/Toronto
permalink: pretty
